
/****** Object:  Table [dbo].[ECC_ENCABEZADO_CARGA]    Script Date: 24/11/2017 0:45:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ECC_ENCABEZADO_CARGA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ARCHIVO] [varchar](550) NULL,
	[FECHA] [datetime] NULL,
	[FILAS_ERROR] [int] NULL,
	[FILAS_CORRECTAS] [int] NULL,
	[INT_ID] [int] NULL,
	[RESUMEN] [varchar](3000) NULL,
 CONSTRAINT [PK_ECC_ENCABEZADO_CARGA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LCM_LOG_CARGA]    Script Date: 24/11/2017 0:45:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LCM_LOG_CARGA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ECC_ID] [int] NULL,
	[NUMERO_FILA] [int] NULL,
	[NOMBRE_USUARIO] [varchar](500) NULL,
	[DETALLE] [varchar](1000) NULL,
	[TIPO_MENSAJE] [int] NULL,
 CONSTRAINT [PK_LCM_LOG_CARGA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
